import Head from "next/head";
import React from "react";

const NewPassword = () => {
  return (
    <>
      <Head>
        <title>Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center justify-center gap-3">
        <p>Nothing to see here</p>
      </main>
    </>
  );
};

export default NewPassword;
