import UserSettingsLayout from "@/components/Layout/UserSettingsLayout";
import Modal from "@/components/Modal/Modal";
import SetupWallet from "@/components/Wallet/SetupWallet";
import WalletInfo from "@/components/Wallet/WalletInfo";
import { NextPageWithLayout } from "@/pages/_app";
import { useUser } from "@/store/user/useUser";
import Head from "next/head";
import React, { ReactElement } from "react";

const Platypay: NextPageWithLayout = () => {
  const walletData = useUser.use.walletData();

  return (
    <>
      <Head>
        <title>Platypay Wallet | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="h-full w-full">
        <Modal backDropClose />
        {walletData ? <WalletInfo /> : <SetupWallet />}
      </main>
    </>
  );
};

Platypay.getLayout = function getLayout(page: ReactElement) {
  return <UserSettingsLayout>{page}</UserSettingsLayout>;
};

export default Platypay;
