import CodeVerificationForm from "@/components/Form/CodeVerificationForm";
import { useToast } from "@/components/ui/use-toast";
import service from "@/services/services";
import { useUser } from "@/store/user/useUser";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { FiMail } from "react-icons/fi";
import { LiaArrowRightSolid } from "react-icons/lia";

const ResetPassword = () => {
  const [send, setSend] = useState(false);
  const { getUserData } = useUser.getState();
  const userData = useUser.use.userData();
  const { toast } = useToast();

  useEffect(() => {
    getUserData();
  }, []);

  const handleSendEmailOTP = async () => {
    const { error, data, message } = await service.postSendOTPChangePassword();

    if (error && message) {
      toast({ title: message, variant: "destructive" });
    } else if (error && data) {
      toast({ title: data.message, variant: "destructive" });
    } else {
      setSend(true);
    }
  };

  return (
    <>
      <Head>
        <title>Change Password | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center justify-center gap-3">
        {send ? (
          <>
            <p className="text-center text-lg font-bold text-primary">
              Verify your code
            </p>
            <p className="px-5 text-xs">
              Verification code has been sent, check your verification code in
              your email
            </p>
            <div>
              <CodeVerificationForm />
            </div>
          </>
        ) : (
          <>
            <p className="text-center text-lg font-bold text-primary">
              Select Verification Method
            </p>
            <div onClick={handleSendEmailOTP} className="group relative">
              <div
                id="verif-reset-pwd-email"
                className="flex w-fit cursor-pointer items-center gap-4 rounded-lg p-5 py-3 text-sm shadow-md"
              >
                <FiMail className="h-7 w-7 text-primary" />
                <div>
                  <p>Send verification code to email</p>
                  <p>{userData?.email}</p>
                </div>
              </div>
              <LiaArrowRightSolid className=" absolute -right-2 top-0 flex h-full w-7 translate-x-0 cursor-pointer items-center justify-center rounded-lg p-1 opacity-0 shadow-md transition duration-500 group-hover:translate-x-full group-hover:opacity-100 group-hover:transition group-hover:duration-500" />
            </div>
          </>
        )}
      </main>
    </>
  );
};

export default ResetPassword;
