import TransactionsHistoryCard from "@/components/Card/TransactionHistoryCard";
import UserSettingsLayout from "@/components/Layout/UserSettingsLayout";
import Modal from "@/components/Modal/Modal";
import UniPagination from "@/components/Pagination/UniPagination";
import PlatypusHead from "@/components/SVG/PlatypusHead";
import { NextPageWithLayout } from "@/pages/_app";
import { useUser } from "@/store/user/useUser";
import Head from "next/head";
import React, { ReactElement, useEffect, useState } from "react";

const Transactions: NextPageWithLayout = () => {
  const { getUserTransaction } = useUser.getState();
  const userTransactions = useUser.use.userTransactions();
  const pageInformation = useUser.use.pageInformation();
  const [pageManagement, setPageManagement] = useState<{
    page: number;
  }>({
    page: 1,
  });

  useEffect(() => {
    getUserTransaction(pageManagement.page);
  }, [pageManagement]);

  if (!userTransactions) {
    return (
      <main className="flex h-full flex-col items-center justify-center gap-3 p-5">
        <span className="loading loading-dots loading-lg text-primary"></span>
      </main>
    );
  }

  const onClickChangePage = (key: string, value: number) => {
    setPageManagement({
      ...pageManagement,
      [key]: value,
    });
  };

  const onClickNextChangePage = (key: string) => {
    setPageManagement({
      ...pageManagement,
      [key]: pageManagement.page + 1,
    });
  };

  const onClickPrevChangePage = (key: string) => {
    setPageManagement({
      ...pageManagement,
      [key]: pageManagement.page - 1,
    });
  };

  if (!pageInformation) {
    return (
      <>
        <Head>
          <title>User Transactions | Platypus</title>
          <meta name="platypus" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/vm4/favicon.ico" />
        </Head>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>User Transactions | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <Modal backDropClose />
      <main>
        <div className="flex w-full flex-col items-center gap-y-3">
          <h1 className="w-full pb-5 text-center text-lg font-bold text-primary md:text-xl">
            Transaction History
          </h1>
          {userTransactions.length == null && (
            <div className="flex w-full items-center justify-center">
              <div className="flex items-center gap-3">
                <PlatypusHead className="h-20 w-20" />
                <div>
                  <p className="text-2x font-bold text-primary">
                    {`You don't have any account address yet`}
                  </p>
                </div>
              </div>
            </div>
          )}
          <div className="my-5 flex justify-center">
            <UniPagination
              onClickChangePage={onClickChangePage}
              onClickNextChangePage={onClickNextChangePage}
              onClickPrevChangePage={onClickPrevChangePage}
              pageInformation={pageInformation}
            />
          </div>
          {userTransactions.length == 0 && (
            <p className="md:px-1">No transactions to show.</p>
          )}
          {userTransactions != null &&
            userTransactions.map((transaction) => {
              return (
                <div
                  className="md:overflow-x-none flex w-full overflow-x-scroll md:justify-center"
                  key={transaction.order_id}
                >
                  <TransactionsHistoryCard
                    key={transaction.order_id}
                    order_id={transaction.order_id}
                    merchant={transaction.merchant}
                    order_price={transaction.order_price}
                  />
                </div>
              );
            })}
          <div className="my-5 flex justify-center">
            <UniPagination
              onClickChangePage={onClickChangePage}
              onClickNextChangePage={onClickNextChangePage}
              onClickPrevChangePage={onClickPrevChangePage}
              pageInformation={pageInformation}
            />
          </div>
        </div>
      </main>
    </>
  );
};

Transactions.getLayout = function getLayout(page: ReactElement) {
  return <UserSettingsLayout>{page}</UserSettingsLayout>;
};

export default Transactions;
