import React, { ReactElement, useEffect } from "react";
import { PiCopyThin } from "react-icons/pi";
import { MdOutlineLocalShipping } from "react-icons/md";
import { FaCircleNotch } from "react-icons/fa";
import Link from "next/link";
import { IoMdInformationCircle } from "react-icons/io";
import UserSellerLayout from "@/components/Layout/UserSellerLayout";
import { useMerchant } from "@/store/merchant/useMerchant";
import { useUser } from "@/store/user/useUser";
import ImageWithFallback from "@/components/ImageWithFallback/ImageWithFallback";
import Head from "next/head";

const MyMerchant = () => {
  const { setMerchant } = useMerchant.getState();
  const merchant = useMerchant.use.merchant();
  const userData = useUser.use.userData();
  useEffect(() => {
    if (userData) {
      const getMerchantData = async () => {
        const response = await fetch(
          `${process.env.BASE_API_URL}/merchants/${userData?.username}`,
        );
        const resultJSON = await response.json();

        const merchant = resultJSON.data;

        setMerchant(merchant);
      };
      getMerchantData();
    }
  }, [userData]);

  if (!merchant) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Merchant Center | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center pt-[90px] md:px-28 md:pt-28 lg:ml-[20vw] 2xl:px-72">
        <div className="flex w-full items-center gap-7 rounded-lg bg-primary/10 p-5 shadow-md md:gap-16 md:px-16">
          <div>
            <ImageWithFallback
              src={merchant.photo}
              loading="lazy"
              alt={merchant.name as string}
              height={300}
              width={300}
              className="absolute z-10 h-24 w-24 rounded-full border-4 border-white bg-white md:h-28 md:w-28"
            />
            <div className="relative h-24 w-24 rounded-full bg-transparent md:h-28 md:w-28">
              <div className="absolute bottom-0 z-10 flex h-5 w-24 items-center justify-center  rounded-tl rounded-tr bg-slate-800 md:w-28">
                <p className="text-[9px] font-medium text-white md:text-[10px] md:font-semibold">
                  Platypus Merchant
                </p>
              </div>
            </div>
          </div>
          <div className="w-full">
            <h1 className="font-semibold">My Merchant</h1>
            <h2>{merchant.name}</h2>
            <div className="flex items-center gap-2">
              <p className="text-sm">{merchant.user_name}</p>
              <PiCopyThin />
            </div>
          </div>
        </div>
        <div className="mt-5 w-full rounded-lg bg-background p-3 shadow-md">
          <div className="mb-5 flex items-center gap-2">
            <IoMdInformationCircle />
            <h1 className="font-medium">Welcome to Merchant Center!</h1>
          </div>
          <p className="text-xs md:text-base">
            Selling on Platypus is easy! Can be accessed via computer or
            directly from the Platypus Merchant application. No need to be
            confused anymore about where to start a business, in this video we
            discuss the A to Z methods. For those who are just starting out, you
            really have to watch it until the end.
          </p>
        </div>
        <div className="mt-5 w-full rounded-lg border-y bg-background px-3 py-5 shadow-md">
          <div className="flex justify-between">
            <h2 className="font-medium">ORDERS</h2>
            <Link
              href={"/merchant-center/manage-orders"}
              className="text-sm text-primary hover:underline"
            >
              Show All
            </Link>
          </div>
          <div className="mt-5 flex gap-5">
            <Link
              href={"/merchant-center/manage-orders"}
              className="flex h-[60px] w-[180px] items-center justify-center gap-2 bg-primary text-sm font-bold text-white shadow"
            >
              <MdOutlineLocalShipping />
              <p>Ready to Ship</p>
            </Link>
            <Link
              href={"/merchant-center/manage-orders"}
              className="flex h-[60px] w-[180px] items-center justify-center gap-2 bg-primary text-sm font-bold text-white shadow"
            >
              <FaCircleNotch />
              <p>Waiting for payment</p>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

MyMerchant.getLayout = function getLayout(page: ReactElement) {
  return <UserSellerLayout>{page}</UserSellerLayout>;
};

export default MyMerchant;
