import React, { ReactElement, useEffect } from "react";
import UserSellerLayout from "@/components/Layout/UserSellerLayout";
import { useUser } from "@/store/user/useUser";
import AddressList from "@/components/UserAddress/AddressList";
import Head from "next/head";

const ManageAddress = () => {
  const { getUserAddresses } = useUser.getState();
  const userAddresses = useUser.use.userAddresses();
  const defaultAddress = useUser.use.defaultAddress();
  useEffect(() => {
    getUserAddresses();
  }, []);

  if (!userAddresses) {
    return (
      <>
        <Head>
          <title>Seller Manage Address | Platypus</title>
          <meta name="platypus" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/vm4/favicon.ico" />
        </Head>
        <main className="flex h-full flex-col items-center justify-center gap-3 p-5">
          <span className="loading loading-dots loading-lg text-primary"></span>
        </main>
      </>
    );
  }

  return (
    <main className="min-w-screen flex min-h-screen flex-col items-center md:px-32 lg:ml-[20vw]">
      <div className="w-[93%] md:w-full">
        <div id="new-promotion-form" className="mb-20 mt-10 max-lg:mt-40">
          <h2 className="mb-5 text-xl font-bold text-primary md:text-4xl">
            Manage Address
          </h2>
          <div className=" rounded-lg border-[1px] border-border bg-background p-5 shadow-md md:w-full md:p-10">
            <h2 className="pb-2 font-bold  text-primary md:pb-5 md:text-lg">
              Set Shop Location
            </h2>

            <div className="grid gap-3 md:grid-cols-2">
              {defaultAddress &&
                defaultAddress.map((address) => {
                  return (
                    <AddressList
                      isActive={address.is_default || address.is_shop_location}
                      key={address.id}
                      addressData={address}
                    />
                  );
                })}
              {userAddresses.map((address) => {
                if (!address.is_default && !address.is_shop_location)
                  return (
                    <AddressList
                      isActive={address.is_default}
                      key={address.id}
                      addressData={address}
                    />
                  );
              })}
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

ManageAddress.getLayout = function getLayout(page: ReactElement) {
  return <UserSellerLayout>{page}</UserSellerLayout>;
};

export default ManageAddress;
