import React, { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import UserLayout from "@/components/Layout/UserLayout";
import PlatypusBlangkon from "@/components/SVG/PlatypusBlangkon";
import Head from "next/head";

const About: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>About | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center pt-24 lg:pt-40">
        <PlatypusBlangkon className="w-screen" />
      </main>
    </>
  );
};

About.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};

export default About;
