import UserLayout from "@/components/Layout/UserLayout";
import React, { ReactElement, useEffect } from "react";
import { NextPageWithLayout } from "../_app";
import { useNavBar } from "@/store/navbar/useNavBar";
import CartCard from "@/components/Cart/CartCard";
import { useCart } from "@/store/cart/useCart";
import { FaShoppingCart } from "react-icons/fa";
import { ManageCart } from "@/components/Cart/ManageCart";
import Head from "next/head";
import { Skeleton } from "@/components/ui/skeleton";
import { ManageMobileCart } from "@/components/Cart/ManageMobileCart";
import ModalUpSlide from "@/components/Modal/ModalUpSlide";

const Cart: NextPageWithLayout = () => {
  const navHeight = useNavBar.use.navHeight();
  const { getInitialValue, groupedCart, multiCartAmount } = useCart();

  useEffect(() => {
    getInitialValue();
  }, []);

  if (!multiCartAmount) {
    return (
      <>
        <Head>
          <title>Cart | Platypus</title>
          <meta name="platypus" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/vm4/favicon.ico" />
        </Head>
        <main className="min-w-screen min-h-screen gap-3 px-3 pb-10 pt-16 md:px-28 md:pt-36 2xl:px-72 ">
          <ModalUpSlide backDropClose />
          <div className="mb-5 flex items-center gap-3 text-4xl text-primary">
            <h1 className=" text-4xl font-bold ">Cart</h1>
            <FaShoppingCart className="justify-start" />
          </div>
          <div className="flex h-full w-full gap-5">
            <div className="h-full w-full flex-[2] gap-4 space-y-3">
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
            </div>
            <div className="h-full w-full flex-1">
              <Skeleton className="h-80 w-full" />
            </div>
          </div>
        </main>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Cart | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen min-h-screen gap-3 px-3 pb-10 pt-16 md:px-28 md:pt-36 2xl:px-72 ">
        <ModalUpSlide backDropClose />
        <div className="mb-5 flex items-center gap-3 text-4xl text-primary">
          <h1 className=" text-4xl font-bold  ">Cart</h1>
          <FaShoppingCart className=" justify-start" />
        </div>
        <div className="w-full">
          <section
            id="section1"
            style={{ minHeight: `calc(100vh - ${navHeight}px)` }}
            className="section lg:relative lg:flex lg:gap-3"
          >
            <div className="flex flex-1 flex-col gap-3">
              {groupedCart.map((group, i) => (
                <div
                  key={`${group.merchant_id}-${i}`}
                  className="rounded-lg border-[1px] border-border p-3 shadow-md lg:p-5"
                >
                  <p className="mb-3 font-bold lg:text-lg">
                    {group.merchant_name}
                  </p>
                  {multiCartAmount.map((cartItem) => {
                    if (cartItem.merchant_id === group.merchant_id) {
                      return (
                        <CartCard
                          key={cartItem.cart_product_id}
                          itemAmount={cartItem}
                        />
                      );
                    }
                  })}
                </div>
              ))}
            </div>
            <ManageMobileCart />
            <div
              style={{ top: `${navHeight + 20}px` }}
              className={`left-0 hidden h-fit w-full rounded-lg border-[1px] border-border bg-background shadow-md lg:sticky lg:block lg:h-fit lg:w-64 xl:w-80`}
            >
              <ManageCart />
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Cart;

Cart.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};
