import React, { ReactElement } from "react";
import { AddProductForm } from "@/components/Form/AddProductForm";
import UserSellerLayout from "@/components/Layout/UserSellerLayout";
import Modal from "@/components/Modal/Modal";
import Head from "next/head";

const AddProduct = () => {
  return (
    <>
      <Head>
        <title>Add Product | Seller Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col px-3 lg:ml-[20vw] lg:px-32">
        <Modal backDropClose />
        <AddProductForm />
      </main>
    </>
  );
};

AddProduct.getLayout = function getLayout(page: ReactElement) {
  return <UserSellerLayout>{page}</UserSellerLayout>;
};

export default AddProduct;
