import ResetPasswordForm from "@/components/Form/ResetPasswordForm";
import Head from "next/head";
import React from "react";

const ResetPassword = () => {
  return (
    <>
      <Head>
        <title>Forgot Password | Platypus</title>
        <meta name="platypus" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vm4/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center justify-center gap-3">
        <p className="text-center text-lg font-bold text-primary">
          Forgot/Reset Your Account Password
        </p>
        <p className="px-5 text-xs">
          Enter your email address to reset the password
        </p>
        <div>
          <ResetPasswordForm />
        </div>
      </main>
    </>
  );
};

export default ResetPassword;
